# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.6)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6...3.20)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget NPTPCDRUM NPCore NPPhysics NPTrackReconstruction NPCalibration NPOnline NPNeutron)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target NPTPCDRUM
add_library(NPTPCDRUM SHARED IMPORTED)

set_target_properties(NPTPCDRUM PROPERTIES
  INTERFACE_LINK_LIBRARIES "dl;Gui;Core;RIO;Net;Hist;Gpad;Tree;Physics;MathCore;Thread;ASImage;NPCore"
)

# Create imported target NPCore
add_library(NPCore SHARED IMPORTED)

set_target_properties(NPCore PROPERTIES
  INTERFACE_LINK_LIBRARIES "dl;Gui;Core;RIO;Net;Hist;Gpad;Tree;Physics;MathCore;Thread;ASImage;-lTreePlayer;-lXMLIO"
)

# Create imported target NPPhysics
add_library(NPPhysics SHARED IMPORTED)

set_target_properties(NPPhysics PROPERTIES
  INTERFACE_LINK_LIBRARIES "dl;Gui;Core;RIO;Net;Hist;Gpad;Tree;Physics;MathCore;Thread;ASImage;Physics;NPCore"
)

# Create imported target NPTrackReconstruction
add_library(NPTrackReconstruction SHARED IMPORTED)

set_target_properties(NPTrackReconstruction PROPERTIES
  INTERFACE_LINK_LIBRARIES "dl;Gui;Core;RIO;Net;Hist;Gpad;Tree;Physics;MathCore;Thread;ASImage;NPCore"
)

# Create imported target NPCalibration
add_library(NPCalibration SHARED IMPORTED)

set_target_properties(NPCalibration PROPERTIES
  INTERFACE_LINK_LIBRARIES "dl;Gui;Core;RIO;Net;Hist;Gpad;Tree;Physics;MathCore;Thread;ASImage;-lSpectrum;NPCore;NPPhysics"
)

# Create imported target NPOnline
add_library(NPOnline SHARED IMPORTED)

set_target_properties(NPOnline PROPERTIES
  INTERFACE_LINK_LIBRARIES "dl;Gui;Core;RIO;Net;Hist;Gpad;Tree;Physics;MathCore;Thread;ASImage;Thread;NPCore"
)

# Create imported target NPNeutron
add_library(NPNeutron SHARED IMPORTED)

set_target_properties(NPNeutron PROPERTIES
  INTERFACE_LINK_LIBRARIES "dl;Gui;Core;RIO;Net;Hist;Gpad;Tree;Physics;MathCore;Thread;ASImage;NPCore"
)

# Import target "NPTPCDRUM" for configuration "Release"
set_property(TARGET NPTPCDRUM APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(NPTPCDRUM PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sghwang/workspace/nptool/NPLib/lib/libNPTPCDRUM.so"
  IMPORTED_SONAME_RELEASE "libNPTPCDRUM.so"
  )

# Import target "NPCore" for configuration "Release"
set_property(TARGET NPCore APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(NPCore PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sghwang/workspace/nptool/NPLib/lib/libNPCore.so"
  IMPORTED_SONAME_RELEASE "libNPCore.so"
  )

# Import target "NPPhysics" for configuration "Release"
set_property(TARGET NPPhysics APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(NPPhysics PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sghwang/workspace/nptool/NPLib/lib/libNPPhysics.so"
  IMPORTED_SONAME_RELEASE "libNPPhysics.so"
  )

# Import target "NPTrackReconstruction" for configuration "Release"
set_property(TARGET NPTrackReconstruction APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(NPTrackReconstruction PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sghwang/workspace/nptool/NPLib/lib/libNPTrackReconstruction.so"
  IMPORTED_SONAME_RELEASE "libNPTrackReconstruction.so"
  )

# Import target "NPCalibration" for configuration "Release"
set_property(TARGET NPCalibration APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(NPCalibration PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sghwang/workspace/nptool/NPLib/lib/libNPCalibration.so"
  IMPORTED_SONAME_RELEASE "libNPCalibration.so"
  )

# Import target "NPOnline" for configuration "Release"
set_property(TARGET NPOnline APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(NPOnline PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sghwang/workspace/nptool/NPLib/lib/libNPOnline.so"
  IMPORTED_SONAME_RELEASE "libNPOnline.so"
  )

# Import target "NPNeutron" for configuration "Release"
set_property(TARGET NPNeutron APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(NPNeutron PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sghwang/workspace/nptool/NPLib/lib/libNPNeutron.so"
  IMPORTED_SONAME_RELEASE "libNPNeutron.so"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
